import {
    Box,
    Boxes,
    CircleCheckBig,
    CreditCard,
    Package,
    Send,
    Truck,
} from "lucide-react";

export const staffs = [
    {
        id: 1,
        name: "Courtney Henry",
        picture: "/dashboard-images/staff-2.jpg",
    },
    {
        id: 2,
        name: "Cameron Williamson",
        picture: "/dashboard-images/staff-1.jpg",
    },
    {
        id: 3,
        name: "Courtney Henry",
        picture: "/dashboard-images/staff-2.jpg",
    },
    {
        id: 4,
        name: "Cameron Williamson",
        picture: "/dashboard-images/staff-1.jpg",
    },
    {
        id: 5,
        name: "Courtney Henry",
        picture: "/dashboard-images/staff-2.jpg",
    },
    {
        id: 6,
        name: "Cameron Williamson",
        picture: "/dashboard-images/staff-1.jpg",
    },
    {
        id: 7,
        name: "Courtney Hnery",
        picture: "/dashboard-images/staff-2.jpg",
    },
    {
        id: 8,
        name: "Cameron Williamson",
        picture: "/dashboard-images/staff-1.jpg",
    },
    {
        id: 9,
        name: "Courtney Hnery",
        picture: "/dashboard-images/staff-2.jpg",
    },
    {
        id: 10,
        name: "Cameron Williamson",
        picture: "/dashboard-images/staff-1.jpg",
    },
    {
        id: 11,
        name: "Courtney Hnery",
        picture: "/dashboard-images/staff-2.jpg",
    },
    {
        id: 12,
        name: "Cameron Williamson",
        picture: "/dashboard-images/staff-1.jpg",
    },
    {
        id: 13,
        name: "Courtney Hnery",
        picture: "/dashboard-images/staff-2.jpg",
    },
    {
        id: 14,
        name: "Cameron Williamson",
        picture: "/dashboard-images/staff-1.jpg",
    },
    {
        id: 15,
        name: "Courtney Hnery",
        picture: "/dashboard-images/staff-2.jpg",
    },
];

export const trackingStats = [
    {
        title: "Total Orders",
        value: 6521,
        change: "+23.5%",
        changeType: "increase",
        Icon: Box,
        path: "",
    },
    {
        title: "In Progress",
        value: 1800,
        change: "-6%",
        changeType: "decrease",
        Icon: Boxes,
        path: "in-progress",
    },
    {
        title: "On Pending",
        value: "1000",
        change: "-7.3%",
        changeType: "decrease",
        Icon: Truck,
        path: "pending",
    },
    {
        title: "Delivered",
        value: 1840,
        change: "+23.1%",
        changeType: "increase",
        Icon: CircleCheckBig,
        path: "completed",
    },
];

export const blogs = [
    {
        id: 1,
        title: "Lorem Ipsum",
        content:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
        date: new Date().toLocaleDateString().replaceAll("/", ", "),
        duration: "13 Min",
        picture: "/dashboard-images/blog.png",
    },
    {
        id: 2,
        title: "Lorem Ipsum",
        content:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
        date: new Date().toLocaleDateString().replaceAll("/", ", "),
        duration: "13 Min",
        picture: "/dashboard-images/blog.png",
    },
    {
        id: 3,
        title: "Lorem Ipsum",
        content:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
        date: new Date().toLocaleDateString().replaceAll("/", ", "),
        duration: "13 Min",
        picture: "/dashboard-images/blog.png",
    },
];

export const shipments = [
    {
        id: 1,
        shipmentNo: "#001234ABCD",
        start: "87 Wern Ddu Lane",
        end: "15 Vicar Lane",
        details: {
            category: "Electronic",
            distance: "60.41 km",
            estimation: "1d 6h",
            weight: "25kg",
            fee: 1050,
        },
    },
    {
        id: 2,
        shipmentNo: "#001234ABCD",
        start: "40 Broomfield Place",
        end: "44 Helland Bridge",
        details: {
            category: "Electronic",
            distance: "60.41 km",
            estimation: "1d 6h",
            weight: "25kg",
            fee: 1050,
        },
    },
    {
        id: 3,
        shipmentNo: "#00124BCD",
        start: "40 Broomfield Place",
        end: "44 Helland Bridge",
        details: {
            category: "Electronic",
            distance: "60.41 km",
            estimation: "1d 6h",
            weight: "25kg",
            fee: 1050,
        },
    },
    {
        id: 4,
        shipmentNo: "#01234CD",
        start: "40 Broomfield Place",
        end: "44 Helland Bridge",
        details: {
            category: "Electronic",
            distance: "60.41 km",
            estimation: "1d 6h",
            weight: "25kg",
            fee: 1050,
        },
    },
];

export const dashboardStats = [
    {
        title: "Total Orders",
        value: 6521,
        change: "+1.3%",
        changeType: "increase",
        icon: Truck,
        path: "",
    },
    {
        title: "Pending Orders",
        value: 105,
        change: "-2.1%",
        changeType: "decrease",
        icon: Package,
        path: "pending",
    },
    {
        title: "In Progress",
        value: 502,
        change: "+1.3%",
        changeType: "increase",
        icon: CreditCard,
        path: "in-progress",
    },
    {
        title: "Completed",
        value: 5840,
        change: "-3.1%",
        changeType: "decrease",
        icon: Send,
        path: "completed",
    },
    {
        title: "Cancelled",
        value: 98,
        change: "+2.1%",
        changeType: "increase",
        icon: Send,
        path: "cancelled",
    },
    {
        title: "Broker Revenue",
        value: 20213,
        change: "-3.1%",
        changeType: "increase",
        icon: Send,
        path: "revenue",
    },
];

export const customersList = [
    {
        customerId: "CUST-1001",
        name: "Alice Johnson",
        phone: "+1 (555) 123-4567",
        email: "alice.johnson@example.com",
        location: "New York, NY",
        company: "Skyline Media LLC",
        profilePicture: "/dashboard-images/staff-1.jpg",
        orders: [
            { orderId: "0023456LKH", date: "2025-04-12", status: "Cancelled" },
            {
                orderId: "0045678LMN",
                date: "2025-05-02",
                status: "In Progress",
            },
        ],
        internalNotes:
            "Prefers communication via email. Loyal customer since 2022.",
    },
    {
        customerId: "CUST-1002",
        name: "Brian Martinez",
        phone: "+1 (555) 234-7890",
        email: "brian.martinez@example.com",
        location: "Austin, TX",
        company: "LumenTech Solutions",
        profilePicture: "/dashboard-images/staff-2.jpg",
        orders: [
            { orderId: "0045678LMN", date: "2025-03-28", status: "Completed" },
        ],
        internalNotes: "Requested priority handling for all orders.",
    },
    {
        customerId: "CUST-1003",
        name: "Chloe Patel",
        phone: "+1 (555) 345-6789",
        email: "chloe.patel@example.com",
        location: "San Francisco, CA",
        company: null,
        profilePicture: "/dashboard-images/staff-3.jpg",
        orders: [],
        internalNotes:
            "Potential lead for enterprise package. Reach out again in July.",
    },
    {
        customerId: "CUST-1004",
        name: "Daniel Kim",
        phone: "+1 (555) 456-7891",
        email: "daniel.kim@example.com",
        location: "Seattle, WA",
        company: "Northbridge Logistics",
        profilePicture: "/dashboard-images/staff-1.jpg",
        orders: [
            { orderId: "0023456LKH", date: "2025-06-05", status: "Pending" },
        ],
        internalNotes:
            "Often checks on export timelines. Time-sensitive shipments.",
    },
    {
        customerId: "CUST-1005",
        name: "Elena Rivera",
        phone: "+1 (555) 567-8902",
        email: "elena.rivera@example.com",
        location: "Miami, FL",
        company: "Rivera Design Studio",
        profilePicture: "/dashboard-images/staff-2.jpg",
        orders: [
            { orderId: "0045678LMN", date: "2025-04-15", status: "Completed" },
        ],
        internalNotes:
            "Had an issue with last cancellation. May need follow-up.",
    },
    {
        customerId: "CUST-1006",
        name: "Farid Al-Sayed",
        phone: "+1 (555) 678-9012",
        email: "farid.sayed@example.com",
        location: "Chicago, IL",
        company: "Greenstone Imports",
        profilePicture: "/dashboard-images/staff-3.jpg",
        orders: [
            { orderId: "001234ABCD", date: "2025-05-27", status: "Completed" },
            {
                orderId: "0023456LKH",
                date: "2025-06-10",
                status: "In Progress",
            },
        ],
        internalNotes: "International customer. Needs invoices in PDF format.",
    },
    {
        customerId: "CUST-1007",
        name: "Grace Liu",
        phone: "+1 (555) 789-0123",
        email: "grace.liu@example.com",
        location: "Boston, MA",
        company: "Nova Systems",
        profilePicture: "/dashboard-images/staff-1.jpg",
        orders: [],
        internalNotes: "New sign-up. No orders yet. Sent onboarding email.",
    },
    {
        customerId: "CUST-1008",
        name: "Hassan Malik",
        phone: "+1 (555) 890-1234",
        email: "hassan.malik@example.com",
        location: "Dallas, TX",
        company: "Malik Brothers Export",
        profilePicture: "/dashboard-images/staff-2.jpg",
        orders: [
            { orderId: "0034567XYZ", date: "2025-06-20", status: "Completed" },
        ],
        internalNotes: "Prefers call updates. Responsive during weekdays only.",
    },
];

export const trackingOrderData = [
    {
        key: "1",
        orderId: "001234ABCD",
        status: "Completed",
        customerName: "Elena Rivera",
        businessName: "Rivera Imports",
        customerEmail: "elena.rivera@example.com",
        customerPhone: "+1 (555) 567-8902",
        notes: "Electronics shipment - ensure waterproof packaging",
        orderAmount: 1050,
        productDetails: `Model: Smart Speaker\nQuantity: 10\nType: Electronics\nCustom specs: Voice Assistant Enabled`,
        category: "Electronic",
        arrivalTime: "7/1/2023",
        weight: "25kg",
        route: "87 Wem Ddu Lane → 15 Vicar Lane",
        brokerRevenue: 150,
        files: [{ name: "invoice_elena.pdf", type: "pdf", visible: true }],
    },
    {
        key: "2",
        orderId: "0023456LKH",
        status: "Pending",
        customerName: "Mark Jennings",
        businessName: "Jennings Corp",
        customerEmail: "mark.jen@example.com",
        customerPhone: "+1 (555) 123-4567",
        notes: "Handle with care - fragile items included",
        orderAmount: 25000,
        productDetails: `Model: Deluxe Furniture Set\nQuantity: 3\nType: Living Room Furniture\nCustom specs: Custom upholstery in navy blue\nDelivery info: Ground floor delivery required`,
        category: "Furniture",
        arrivalTime: "7/3/2023",
        weight: "50kg",
        route: "40 Broomfield Place → 44 Helland Bridge",
        brokerRevenue: 2200,
        files: [
            { name: "invoice_001.pdf", type: "pdf", visible: true },
            { name: "product_specs.jpg", type: "image", visible: true },
        ],
    },
    {
        key: "3",
        orderId: "0034567XYZ",
        status: "In Progress",
        customerName: "Sarah Lee",
        businessName: "Lee Fashion Co.",
        customerEmail: "sarah.lee@example.com",
        customerPhone: "+1 (555) 888-4321",
        notes: "Clothing shipment with seasonal stock",
        orderAmount: 800,
        productDetails: `Type: Summer Clothing\nQuantity: 100 units\nSpecial instructions: Folded & poly-bagged`,
        category: "Clothing",
        arrivalTime: "7/5/2023",
        weight: "50kg",
        route: "11 Walden Road → 39 Grenoble Road",
        brokerRevenue: 120,
        files: [],
    },
    {
        key: "4",
        orderId: "0045678LMN",
        status: "Cancelled",
        customerName: "Ivan Petrov",
        businessName: "Petrov Interiors",
        customerEmail: "ivan.petrov@example.ru",
        customerPhone: "+7 (495) 123-4567",
        notes: "Cancelled due to route change",
        orderAmount: 2200,
        productDetails: `Type: Office Desks\nQuantity: 5\nCustom: Dark oak finish`,
        category: "Furniture",
        arrivalTime: "7/6/2023",
        weight: "50kg",
        route: "London → Moscow",
        brokerRevenue: 180,
        files: [],
    },
    {
        key: "5",
        orderId: "0056789ABC",
        status: "In Progress",
        customerName: "Akira Sato",
        businessName: "Sato Motors",
        customerEmail: "akira.sato@example.jp",
        customerPhone: "+81 80-1234-5678",
        notes: "Handle as priority shipment",
        orderAmount: 4000,
        productDetails: `Model: Altima\nType: Automobile\nSpecs: Full tank & clean interior`,
        category: "Automobile",
        arrivalTime: "7/7/2023",
        weight: "1500kg",
        route: "Tokyo → Seattle",
        brokerRevenue: 600,
        files: [{ name: "car_export_docs.pdf", type: "pdf", visible: true }],
    },
    {
        key: "6",
        orderId: "0067890DEF",
        status: "Completed",
        customerName: "Clara Weiss",
        businessName: "Weiss Electronics",
        customerEmail: "clara.weiss@example.de",
        customerPhone: "+49 30 123456",
        notes: "Includes warranty slips",
        orderAmount: 1800,
        productDetails: `Model: Dishwasher ProX\nQuantity: 4\nSpecs: Energy efficient, stainless steel`,
        category: "Appliances",
        arrivalTime: "7/8/2023",
        weight: "300kg",
        route: "Berlin → Paris",
        brokerRevenue: 250,
        files: [],
    },
    {
        key: "7",
        orderId: "0078901GHI",
        status: "Pending",
        customerName: "Luca Moretti",
        businessName: "Moretti MedTech",
        customerEmail: "luca.moretti@example.it",
        customerPhone: "+39 02 123456",
        notes: "Medical shipment - keep at room temperature",
        orderAmount: 950,
        productDetails: `Type: Diagnostic Equipment\nQuantity: 8 units`,
        category: "Medical",
        arrivalTime: "7/9/2023",
        weight: "80kg",
        route: "Zurich → Milan",
        brokerRevenue: 130,
        files: [],
    },
    {
        key: "8",
        orderId: "0089012JKL",
        status: "Completed",
        customerName: "Ravi Patel",
        businessName: "Patel Industrial Machines",
        customerEmail: "ravi.patel@example.in",
        customerPhone: "+91 9876543210",
        notes: "Heavy machinery - forklift required",
        orderAmount: 5600,
        productDetails: `Model: TurboDrill 9000\nQuantity: 2\nSpecs: Oil rig compatible`,
        category: "Machinery",
        arrivalTime: "7/10/2023",
        weight: "2000kg",
        route: "Mumbai → Dubai",
        brokerRevenue: 900,
        files: [],
    },
    {
        key: "9",
        orderId: "0090123MNO",
        status: "Cancelled",
        customerName: "Jin Woo",
        businessName: "SeoulTech",
        customerEmail: "jin.woo@example.kr",
        customerPhone: "+82 10-1234-5678",
        notes: "Cancelled due to customs delay",
        orderAmount: 1200,
        productDetails: `Type: Computer Monitors\nQuantity: 50`,
        category: "Electronics",
        arrivalTime: "7/11/2023",
        weight: "20kg",
        route: "Seoul → San Francisco",
        brokerRevenue: 140,
        files: [],
    },
    {
        key: "10",
        orderId: "0101234PQR",
        status: "Pending",
        customerName: "Emily Clark",
        businessName: "Clark Toys Inc",
        customerEmail: "emily.clark@example.com",
        customerPhone: "+1 (555) 234-5678",
        notes: "Children's toys - safety compliance needed",
        orderAmount: 655,
        productDetails: `Type: Building Blocks\nQuantity: 500 sets`,
        category: "Toys",
        arrivalTime: "7/12/2023",
        weight: "40kg",
        route: "New York → Toronto",
        brokerRevenue: 90,
        files: [],
    },
    {
        key: "11",
        orderId: "0112345STU",
        status: "Completed",
        customerName: "Patrick O'Brien",
        businessName: "O'Brien Bookstores",
        customerEmail: "patrick.obrien@example.ie",
        customerPhone: "+353 1 234 5678",
        notes: "Books for back-to-school inventory",
        orderAmount: 720,
        productDetails: `Type: Educational Books\nQuantity: 300`,
        category: "Books",
        arrivalTime: "7/13/2023",
        weight: "15kg",
        route: "Boston → Dublin",
        brokerRevenue: 95,
        files: [],
    },
    {
        key: "12",
        orderId: "0123456VWX",
        status: "In Progress",
        customerName: "Putri Ayu",
        businessName: "Ayu Health Supplies",
        customerEmail: "putri.ayu@example.id",
        customerPhone: "+62 21 12345678",
        notes: "Pack in sterile packaging",
        orderAmount: 1000,
        productDetails: `Type: First-aid kits\nQuantity: 120`,
        category: "Medical",
        arrivalTime: "7/14/2023",
        weight: "75kg",
        route: "Bangkok → Jakarta",
        brokerRevenue: 160,
        files: [],
    },
    {
        key: "13",
        orderId: "0134567YZA",
        status: "Cancelled",
        customerName: "Amine El Idrissi",
        businessName: "Casablanca Garments",
        customerEmail: "amine.idrissi@example.ma",
        customerPhone: "+212 6 12345678",
        notes: "Cancelled - shipment not ready",
        orderAmount: 85,
        productDetails: `Type: Casual Wear\nQuantity: 75`,
        category: "Clothing",
        arrivalTime: "7/15/2023",
        weight: "30kg",
        route: "Madrid → Casablanca",
        brokerRevenue: 10,
        files: [],
    },
    {
        key: "14",
        orderId: "0145678BCD",
        status: "Completed",
        customerName: "Mika Tanaka",
        businessName: "Tanaka Appliances",
        customerEmail: "mika.tanaka@example.jp",
        customerPhone: "+81 90-1234-5678",
        notes: "Ensure voltage compatibility",
        orderAmount: 1300,
        productDetails: `Type: Kitchen Blenders\nQuantity: 25`,
        category: "Appliances",
        arrivalTime: "7/16/2023",
        weight: "90kg",
        route: "Osaka → Manila",
        brokerRevenue: 170,
        files: [],
    },
    {
        key: "15",
        orderId: "0156789EFG",
        status: "In Progress",
        customerName: "Anni Laine",
        businessName: "LaineTech",
        customerEmail: "anni.laine@example.fi",
        customerPhone: "+358 40 1234567",
        notes: "Include batteries separately",
        orderAmount: 1150,
        productDetails: `Type: Laptops\nQuantity: 20`,
        category: "Electronics",
        arrivalTime: "7/17/2023",
        weight: "28kg",
        route: "Helsinki → Stockholm",
        brokerRevenue: 180,
        files: [],
    },
    {
        key: "16",
        orderId: "0167890HIJ",
        status: "Completed",
        customerName: "Carlos Hernández",
        businessName: "Hernández Auto Co.",
        customerEmail: "carlos.hernandez@example.mx",
        customerPhone: "+52 55 1234 5678",
        notes: "Inspect before final delivery",
        orderAmount: 3800,
        productDetails: `Model: Chevrolet Cruze\nType: Automobile\nSpecs: Cleaned and prepped for delivery`,
        category: "Automobile",
        arrivalTime: "7/18/2023",
        weight: "1450kg",
        route: "Chicago → Mexico City",
        brokerRevenue: 500,
        files: [],
    },
];
