export const trackingListData = [
    {
        key: "1",
        orderId: "TRK123456",
        date: "2023-02-15",
        category: "Electronics",
        route: "Jkt–Sby",
        status: "In Transit",
    },
    {
        key: "2",
        orderId: "TRK789012",
        date: "2023-02-18",
        category: "Furniture",
        route: "Bdg–Yyk",
        status: "Shipped",
    },
    {
        key: "3",
        orderId: "TRK345678",
        date: "2023-02-20",
        category: "Electronics",
        route: "Jkt–Yyk",
        status: "Delivered",
    },
    {
        key: "4",
        orderId: "TRK901234",
        date: "2023-02-22",
        category: "Beauty",
        route: "Jkt–Smg",
        status: "In Transit",
    },
    {
        key: "5",
        orderId: "TRK567890",
        date: "2023-02-25",
        category: "Books",
        route: "Sby–Jkt",
        status: "Shipped",
    },
    {
        key: "6",
        orderId: "TRK345678",
        date: "2023-03-01",
        category: "Apparel",
        route: "Sby–Mdn",
        status: "Delivered",
    },
];


export const trackingOrderData = [
    {
        key: "1",
        orderId: "#001234ABCD",
        category: "Electronic",
        arrivalTime: "7/1/2023",
        weight: "25kg",
        route: "87 Wem Ddu Lane → 15 Vicar Lane",
        fee: "$1,050",
        status: "Delivered",
    },
    {
        key: "2",
        orderId: "#0023456LKH",
        category: "Furniture",
        arrivalTime: "7/1/2023",
        weight: "50kg",
        route: "40 Broomfield Place → 44 Helland Bridge",
        fee: "$2,200",
        status: "Pending",
    },
    {
        key: "3",
        orderId: "#0023456LKH",
        category: "Clothing",
        arrivalTime: "7/1/2023",
        weight: "50kg",
        route: "11 Walden Road → 39 Grenoble Road",
        fee: "$800",
        status: "Shipping",
    },
    {
        key: "4",
        orderId: "#0023456LKH",
        category: "Furniture",
        arrivalTime: "7/1/2023",
        weight: "50kg",
        route: "London → Moskow",
        fee: "$2,200",
        status: "Pending",
    },
];
