export const customersList = [
    {
        customerId: "CUST-1001",
        name: "Alice Johnson",
        phone: "+1 (555) 123-4567",
        email: "alice.johnson@example.com",
        location: "New York, NY",
        company: "Skyline Media LLC",
        profilePicture: "/dashboard-images/staff-1.jpg",
        orders: [
            { orderId: "0023456LKH", date: "2025-04-12", status: "Shipped" },
            {
                orderId: "0045678LMN",
                date: "2025-05-02",
                status: "In Progress",
            },
        ],
        internalNotes:
            "Prefers communication via email. Loyal customer since 2022.",
    },
    {
        customerId: "CUST-1002",
        name: "Brian Martinez",
        phone: "+1 (555) 234-7890",
        email: "brian.martinez@example.com",
        location: "Austin, TX",
        company: "LumenTech Solutions",
        profilePicture: "/dashboard-images/staff-2.jpg",
        orders: [
            { orderId: "0045678LMN", date: "2025-03-28", status: "Delivered" },
        ],
        internalNotes: "Requested priority handling for all orders.",
    },
    {
        customerId: "CUST-1003",
        name: "Chloe Patel",
        phone: "+1 (555) 345-6789",
        email: "chloe.patel@example.com",
        location: "San Francisco, CA",
        company: null,
        profilePicture: "/dashboard-images/staff-3.jpg",
        orders: [],
        internalNotes:
            "Potential lead for enterprise package. Reach out again in July.",
    },
    {
        customerId: "CUST-1004",
        name: "Daniel Kim",
        phone: "+1 (555) 456-7891",
        email: "daniel.kim@example.com",
        location: "Seattle, WA",
        company: "Northbridge Logistics",
        profilePicture: "/dashboard-images/staff-1.jpg",
        orders: [
            { orderId: "0023456LKH", date: "2025-06-05", status: "Pending" },
        ],
        internalNotes:
            "Often checks on export timelines. Time-sensitive shipments.",
    },
    {
        customerId: "CUST-1005",
        name: "Elena Rivera",
        phone: "+1 (555) 567-8902",
        email: "elena.rivera@example.com",
        location: "Miami, FL",
        company: "Rivera Design Studio",
        profilePicture: "/dashboard-images/staff-2.jpg",
        orders: [
            { orderId: "0045678LMN", date: "2025-04-15", status: "Delivered" },
        ],
        internalNotes:
            "Had an issue with last cancellation. May need follow-up.",
    },
    {
        customerId: "CUST-1006",
        name: "Farid Al-Sayed",
        phone: "+1 (555) 678-9012",
        email: "farid.sayed@example.com",
        location: "Chicago, IL",
        company: "Greenstone Imports",
        profilePicture: "/dashboard-images/staff-3.jpg",
        orders: [
            { orderId: "001234ABCD", date: "2025-05-27", status: "Delivered" },
            { orderId: "0023456LKH", date: "2025-06-10", status: "Processing" },
        ],
        internalNotes: "International customer. Needs invoices in PDF format.",
    },
    {
        customerId: "CUST-1007",
        name: "Grace Liu",
        phone: "+1 (555) 789-0123",
        email: "grace.liu@example.com",
        location: "Boston, MA",
        company: "Nova Systems",
        profilePicture: "/dashboard-images/staff-1.jpg",
        orders: [],
        internalNotes: "New sign-up. No orders yet. Sent onboarding email.",
    },
    {
        customerId: "CUST-1008",
        name: "Hassan Malik",
        phone: "+1 (555) 890-1234",
        email: "hassan.malik@example.com",
        location: "Dallas, TX",
        company: "Malik Brothers Export",
        profilePicture: "/dashboard-images/staff-2.jpg",
        orders: [
            { orderId: "0034567XYZ", date: "2025-06-20", status: "Shipped" },
        ],
        internalNotes: "Prefers call updates. Responsive during weekdays only.",
    },
];

export const trackingOrderData = [
    {
        key: "1",
        orderId: "001234ABCD",
        category: "Electronic",
        arrivalTime: "7/1/2023",
        weight: "25kg",
        route: "87 Wem Ddu Lane → 15 Vicar Lane",
        fee: "$1,050",
        status: "Completed",
        customerName: "Elena Rivera",
        customerEmail: "elena.rivera@example.com",
        customerPhone: "+1 (555) 567-8902",
        vin: "1HGCM82633A123456",
        make: "Toyota",
        model: "Camry",
        year: "2023",
        destinationPort: "Port of Miami",
        shippingDate: "7/15/2023",
    },
    {
        key: "2",
        orderId: "0023456LKH",
        category: "Furniture",
        arrivalTime: "7/3/2023",
        weight: "50kg",
        route: "40 Broomfield Place → 44 Helland Bridge",
        fee: "$2,200",
        status: "Pending",
        customerName: "Mark Jennings",
        customerEmail: "mark.jen@example.com",
        customerPhone: "+1 (555) 123-4567",
        vin: "2HGCM82633A789012",
        make: "Honda",
        model: "Accord",
        year: "2022",
        destinationPort: "Port of Los Angeles",
        shippingDate: "7/18/2023",
    },
    {
        key: "3",
        orderId: "0034567XYZ",
        category: "Clothing",
        arrivalTime: "7/5/2023",
        weight: "50kg",
        route: "11 Walden Road → 39 Grenoble Road",
        fee: "$800",
        status: "In Progress",
        customerName: "Sarah Lee",
        customerEmail: "sarah.lee@example.com",
        customerPhone: "+1 (555) 888-4321",
        vin: "3HGCM82633A654321",
        make: "Ford",
        model: "Fusion",
        year: "2021",
        destinationPort: "Port of New York",
        shippingDate: "7/20/2023",
    },
    {
        key: "4",
        orderId: "0045678LMN",
        category: "Furniture",
        arrivalTime: "7/6/2023",
        weight: "50kg",
        route: "London → Moscow",
        fee: "$2,200",
        status: "Cancelled",
        customerName: "Ivan Petrov",
        customerEmail: "ivan.petrov@example.ru",
        customerPhone: "+7 (495) 123-4567",
        vin: "4HGCM82633A998877",
        make: "BMW",
        model: "X5",
        year: "2024",
        destinationPort: "Port of Saint Petersburg",
        shippingDate: "7/22/2023",
    },
    {
        key: "5",
        orderId: "0056789ABC",
        category: "Automobile",
        arrivalTime: "7/7/2023",
        weight: "1500kg",
        route: "Tokyo → Seattle",
        fee: "$4,000",
        status: "In Progress",
        customerName: "Akira Sato",
        customerEmail: "akira.sato@example.jp",
        customerPhone: "+81 80-1234-5678",
        vin: "JH4KA8270MC012345",
        make: "Nissan",
        model: "Altima",
        year: "2023",
        destinationPort: "Port of Seattle",
        shippingDate: "7/25/2023",
    },
    {
        key: "6",
        orderId: "0067890DEF",
        category: "Appliances",
        arrivalTime: "7/8/2023",
        weight: "300kg",
        route: "Berlin → Paris",
        fee: "$1,800",
        status: "Completed",
        customerName: "Clara Weiss",
        customerEmail: "clara.weiss@example.de",
        customerPhone: "+49 30 123456",
        vin: "WBA3A5C51CF123456",
        make: "Volkswagen",
        model: "Passat",
        year: "2020",
        destinationPort: "Port of Hamburg",
        shippingDate: "7/26/2023",
    },
    {
        key: "7",
        orderId: "0078901GHI",
        category: "Medical",
        arrivalTime: "7/9/2023",
        weight: "80kg",
        route: "Zurich → Milan",
        fee: "$950",
        status: "Pending",
        customerName: "Luca Moretti",
        customerEmail: "luca.moretti@example.it",
        customerPhone: "+39 02 123456",
        vin: "ZFAAXX00X0P012345",
        make: "Fiat",
        model: "500",
        year: "2022",
        destinationPort: "Port of Genoa",
        shippingDate: "7/27/2023",
    },
    {
        key: "8",
        orderId: "0089012JKL",
        category: "Machinery",
        arrivalTime: "7/10/2023",
        weight: "2000kg",
        route: "Mumbai → Dubai",
        fee: "$5,600",
        status: "Completed",
        customerName: "Ravi Patel",
        customerEmail: "ravi.patel@example.in",
        customerPhone: "+91 9876543210",
        vin: "MAJ6P1CL6JC123456",
        make: "Tata",
        model: "Harrier",
        year: "2023",
        destinationPort: "Port of Dubai",
        shippingDate: "7/28/2023",
    },
    {
        key: "9",
        orderId: "0090123MNO",
        category: "Electronics",
        arrivalTime: "7/11/2023",
        weight: "20kg",
        route: "Seoul → San Francisco",
        fee: "$1,200",
        status: "Cancelled",
        customerName: "Jin Woo",
        customerEmail: "jin.woo@example.kr",
        customerPhone: "+82 10-1234-5678",
        vin: "KMHEC4A47FA123456",
        make: "Hyundai",
        model: "Elantra",
        year: "2022",
        destinationPort: "Port of Oakland",
        shippingDate: "7/29/2023",
    },
    {
        key: "10",
        orderId: "0101234PQR",
        category: "Toys",
        arrivalTime: "7/12/2023",
        weight: "40kg",
        route: "New York → Toronto",
        fee: "$650",
        status: "Pending",
        customerName: "Emily Clark",
        customerEmail: "emily.clark@example.com",
        customerPhone: "+1 (555) 234-5678",
        vin: "1C4RJEBG6JC123456",
        make: "Jeep",
        model: "Grand Cherokee",
        year: "2021",
        destinationPort: "Port of Toronto",
        shippingDate: "7/30/2023",
    },
    {
        key: "11",
        orderId: "0112345STU",
        category: "Books",
        arrivalTime: "7/13/2023",
        weight: "15kg",
        route: "Boston → Dublin",
        fee: "$720",
        status: "Completed",
        customerName: "Patrick O'Brien",
        customerEmail: "patrick.obrien@example.ie",
        customerPhone: "+353 1 234 5678",
        vin: "5N1AR2MM6FC123456",
        make: "Nissan",
        model: "Rogue",
        year: "2019",
        destinationPort: "Port of Dublin",
        shippingDate: "8/1/2023",
    },
    {
        key: "12",
        orderId: "0123456VWX",
        category: "Medical",
        arrivalTime: "7/14/2023",
        weight: "75kg",
        route: "Bangkok → Jakarta",
        fee: "$1,000",
        status: "In Progress",
        customerName: "Putri Ayu",
        customerEmail: "putri.ayu@example.id",
        customerPhone: "+62 21 12345678",
        vin: "JN8AS5MT0CW123456",
        make: "Mazda",
        model: "CX-5",
        year: "2023",
        destinationPort: "Port of Jakarta",
        shippingDate: "8/2/2023",
    },
    {
        key: "13",
        orderId: "0134567YZA",
        category: "Clothing",
        arrivalTime: "7/15/2023",
        weight: "30kg",
        route: "Madrid → Casablanca",
        fee: "$850",
        status: "Cancelled",
        customerName: "Amine El Idrissi",
        customerEmail: "amine.idrissi@example.ma",
        customerPhone: "+212 6 12345678",
        vin: "WAUFFAFL1DA123456",
        make: "Audi",
        model: "A4",
        year: "2020",
        destinationPort: "Port of Casablanca",
        shippingDate: "8/3/2023",
    },
    {
        key: "14",
        orderId: "0145678BCD",
        category: "Appliances",
        arrivalTime: "7/16/2023",
        weight: "90kg",
        route: "Osaka → Manila",
        fee: "$1,300",
        status: "Completed",
        customerName: "Mika Tanaka",
        customerEmail: "mika.tanaka@example.jp",
        customerPhone: "+81 90-1234-5678",
        vin: "JT2BG22K9V0123456",
        make: "Subaru",
        model: "Outback",
        year: "2021",
        destinationPort: "Port of Manila",
        shippingDate: "8/4/2023",
    },
    {
        key: "15",
        orderId: "0156789EFG",
        category: "Electronics",
        arrivalTime: "7/17/2023",
        weight: "28kg",
        route: "Helsinki → Stockholm",
        fee: "$1,150",
        status: "In Progress",
        customerName: "Anni Laine",
        customerEmail: "anni.laine@example.fi",
        customerPhone: "+358 40 1234567",
        vin: "YS3DD75N4X7054321",
        make: "Saab",
        model: "9-3",
        year: "2022",
        destinationPort: "Port of Stockholm",
        shippingDate: "8/5/2023",
    },
    {
        key: "16",
        orderId: "0167890HIJ",
        category: "Automobile",
        arrivalTime: "7/18/2023",
        weight: "1450kg",
        route: "Chicago → Mexico City",
        fee: "$3,800",
        status: "Completed",
        customerName: "Carlos Hernández",
        customerEmail: "carlos.hernandez@example.mx",
        customerPhone: "+52 55 1234 5678",
        vin: "3VW1K7AJ0EM123456",
        make: "Chevrolet",
        model: "Cruze",
        year: "2023",
        destinationPort: "Port of Veracruz",
        shippingDate: "8/6/2023",
    },
];
